a = float(input("Ingresa el primer número: "))
b = float(input("Ingresa el segundo número: "))
print("Suma: ", a + b)
print("Resta: ", a - b)
print("Multiplicación: ", a * b)
print("División: ", a / b)